### ISSUE TITLE
Insert link with ZettelSearch uses filename instead of title

### ISSUE THREAD

**Issue by gasperphoenix** [michal-h21/vim-zettel#103]
Hi, I am able to create a new zettel using the shortcut. In this case the marked text is correctly used as title for my new zettel.
`= <TITLE> =`

But when I search for a page using [[, select it and press enter a link is added that uses the filename for both the target and the link text. But I expect that it extracts the title from the target page and uses it as link title.
My expectation: `[[<LINK TARGET>|<TARGET TITLE>]]`
Observed behavior: `[[<LINK TARGET>|<LINK TARGET>]]`

Am I doing something wrong?

Please find attached my zettel template - I added the extension .txt to upload it to GitHub:
[zettel_template.tpl.txt](https://github.com/michal-h21/vim-zettel/files/6000848/zettel_template.tpl.txt)

**Comment by gasperphoenix** [comment]
I created pull request #105 with an implementation to improve the behavior

**Comment by Matt-Deacalion** [comment]
I'm having the same issue.

I've just tried the patch by Dennis and it works perfectly with markdown files. Could this be merged?

**Comment by michal-h21** [comment]
Thanks for the patch, title should be detected in the first heading now.
