### ISSUE TITLE
Support for vim-plug

### ISSUE THREAD

**Issue by eorn** [michal-h21/vim-zettel#11]
I was wondering if support for installing with `vim-plug` was possible.
For now `vim-zettel` can only be installed with Vundle, right?

**Comment by michal-h21** [comment]
I don't use `vim-plug` personally, but shouldn't it work out of the box? You can try to put the following lines to your `.vimrc` instead of instructions for Vundle:

```
Plug 'vimwiki/vimwiki'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'michal-h21/vim-zettel'
```

**Comment by eorn** [comment]
Something is indeed installed, but I cannot run `:ZettelNew` somehow… Only `:ZettelCapture` can be ran, and the result is the same as in #10.

However after having tried via Vundle, I have the same issue, so the problem is probably somewhere else.

**Comment by eorn** [comment]
I would add that this happens for both `vim` and `neovim`.
For `vim`, I used an empty `.vimrc`, kept the installation instructions from your Readme, changing the Vundle instructions to vim-plug ones. Appended the sample configuration in the Readme.

`vimwiki` and the other plugins work, and for `vim-zettel` only `:ZettelCapture` seems to exist.

**Comment by eorn** [comment]
I'm not an expert on `vim` plugins. I tried to copy what's in `ftplugin/` into `plugin` and now I can run `:ZettelNew`, it seems to work well.

**Comment by michal-h21** [comment]
I've updated the README, I hope it is more clear now. The majority of `Vim-zettel` commands is available only in the Vimwiki mode, so you need to open Vimwiki first using `:VimwikiIndex` command first.

**Comment by eorn** [comment]
That was it, I had not opened Vimwiki first.
Many thanks, for your answer and your work!
