### ISSUE TITLE
Generate ID in template

### ISSUE THREAD

**Issue by sbock17** [michal-h21/vim-zettel#118]
How would it be possible, to insert a variable, like %id into the template, which behaves the same way as %title or %date, giving just the ID prefix which is also used for the filename?

e.g. when I create a new zettel, 202201101817-Title 
and the template.tpl containing:
```
# %id %title
```

resulting to:

```
# 202201101817 Title
```

How would that be possible?

**Comment by yetipowers** [comment]
Thank you so much for the generous commenting, @michal-h21 !!

I came up with a very simple solution changing one line - replacing the content of the %date variable with a value for the ID in line 170 of the file ~.config/nvim/plugged/vim-zettel/autoload/zettel/vimwiki.vim
```vim
" default date format used in front matter for new zettel
  let g:zettel_date_format = "%Y-%m-%d %H:%M"
```

I just replaced the values to the format corresponding to my zettel_format in the vimwiki.vim (%Y%m%d%H%M), resulting to line 170 in vimwiki.vim:
```vim
  let g:zettel_date_format = "%Y%m%d%H%M" "acting as my id
```

So now, by using the %date variable in the template acting as the ID, 

```md
# %date %title
```
I got to the result I was looking for:

```md
# 202201151258 Title
```

Again thanks a lot for this package, reading through the plugin files is also a great way to learn how it works, as everything is so well documented. :)
