### ISSUE TITLE
Error when creating new Zettel

### ISSUE THREAD

**Issue by tokisuno** [michal-h21/vim-zettel#143]
![image](https://github.com/michal-h21/vim-zettel/assets/85533116/f90750dc-d700-4bdc-87a5-9de0e0e11ae3)

I get this error every time I hit visual+z. Any idea of how to fix this?

**Comment by michal-h21** [comment]
It looks like the selected text gets unselected before the function finish? I am not sure how it would be possible. Which Vim version do you use?

**Comment by tokisuno** [comment]
okay closing this because i just wasn't using the function correctly LMAO. i misread the wiki thinking that vz was the key to make a new zettel (like ZkNew0
