### ISSUE TITLE
General Question: How do you properly use tags?

### ISSUE THREAD

**Issue by tokisuno** [michal-h21/vim-zettel#144]
Howdy! I wanna use tags in my Zettel and then use :ZettelGenerateTags on my index.md to populate it with the different files per tag. I tried using :tag1: - regenerating tags with vimwiki and then launching :ZettelGenerateTags only to get this. 

![image](https://github.com/michal-h21/vim-zettel/assets/85533116/7c8e8c6a-1a38-455a-8035-c5cb7c9d39f2)

**Comment by michal-h21** [comment]
Thanks for the report. The format of the tags file used by Vimwiki changed. I've updated Vim-zettel to support this format, so it should work now.

**Comment by tokisuno** [comment]
confirmed it works. thanks !
