### ISSUE TITLE
Error on :ZettelNew

### ISSUE THREAD

**Issue by ivanvgav** [michal-h21/vim-zettel#15]
I have installed and made the configuration as readme file says, but when I enter into the vimwiki and type the command :ZettelNew it appears: "E492: Not an editor command: ZettelNew".
I'm on neovim rather than vim itself.
I know that it should be a silly question. Beg your pardon.

Regards

**Comment by Andreilys** [comment]
@ivanvgav did you end up resolving this?

**Comment by ivanvgav** [comment]
Yes, I've already solved it. I clean the plug and then reinstalled. Perfectly fine
