### ISSUE TITLE
ZettelNew in Diary creates file in the right folder, but link has missing /

### ISSUE THREAD

**Issue by stoeps13** [michal-h21/vim-zettel#155]
Hi,

when I mark some text in my diary (today for example) and use z to create a new zettel, then the file is generated in the folder below the diary folder, but the link points to `[link text](241125-104947)`, so if I click on this link, the file is created in the diary folder. There should be a `/` before the filename.

Folder structure:

```bash
vimwiki
├── 20241125-104947.md
├── diary
│      ├── 2024-11-25.md
```

My Neovim config:
```
    vim.g.vimwiki_list = {
      {
        path = "~/vimwiki",
        syntax = "markdown",
        ext = ".md",
        links_space_char = "_",
        path_html = "~/vimwiki/site_html/",
        custom_wiki2html = "vimwiki_markdown",
        auto_tags = 1,
        auto_diary_index = 1,
      },
    }
    vim.g.zettel_format = "%y%m%d-%H%M%S"
    vim.g.zettel_options = {
      {
        template = "~/vimwiki/template.tpl",
        disable_front_matter = 1,
      },
    }

```

Is there any config option to add a / before the link to the new zettel?
Regards,
Christoph

**Comment by michal-h21** [comment]
Thanks for the report. This issue was more complicated than adding `/` to links, but it should work now. I've also fixed backlinks, which were broken for subdirectories.

**Comment by stoeps13** [comment]
Looks great! Thanks for the fast update.
