### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by sunnyrahul25** [michal-h21/vim-zettel#20]
Thank you @michal-h21  for creating the plugin. I recently learned about zettlekasten method and exploring the plugin.
I was exploring the tags  command but using ZettleGenerateTags doesn't generate any tags.I am confused about its usage.
It would be helpful if you share some example or workflow. eg. Adding tags manually to a zettle.

**Comment by michal-h21** [comment]
Do you use the Vimwiki syntax, or Markdown. Vimwiki supports only this syntax: `:tag1:tag2:`, even in the Markdown mode. You also need to update the tags manually using `:VimwikiRebuildTags`.

**Comment by sunnyrahul25** [comment]
Thank you,  :tag1:tag2: , works fine. I can now generate tags
