### ISSUE TITLE
FZF rg integration not working

### ISSUE THREAD

**Issue by RyanWillDev** [michal-h21/vim-zettel#22]
Looks like when trying to use the `[[` search mapping with `rg` instead of `ag` there is an undefined function error calling the fzf plugin.

<img width="817" alt="Screen Shot 2020-03-09 at 12 53 43 PM" src="https://user-images.githubusercontent.com/12587988/76242843-57770d80-6205-11ea-8ae4-26397332d73a.png">

Steps to reproduce:
1. `let g:zettel_fzf_command = 'rg'` in `vimrc`
2. Try to use the `[[` key map to create link to another Zettel

I'm not sure how the fzf plugin works, but I'd be happy to take a look or help debug it.

**Comment by michal-h21** [comment]
I hope this issue is fixed now. I've found that it is necessary to use different functions for `Ag` and other grep-like commands. You need to pass necessary options to `rg`.

From README:

```
" default value is "ag". To use other command, like ripgrep, pass the
" command line and options:
let g:zettel_fzf_command = "rg --column --line-number --ignore-case --no-heading --color=always "
```

**Comment by RyanWillDev** [comment]
I also had trouble getting all the commands to run using `fzf#vim#grep` I tried to use [fzf#run](https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun) instead but had trouble getting that to work as well. 

Your changes seemed to fix this issue, though. Thanks a ton!

**Comment by michal-h21** [comment]
Great! I plan to introduce more commands based on FZF, so I am happy that I understand better how it works now.
