### ISSUE TITLE
ZettelInbox not reporting all unlinked pages

### ISSUE THREAD

**Issue by hackabletype** [michal-h21/vim-zettel#25]
Despite having several new, unlinked Zettel files, `:ZettelInbox` is only generating this for me:
```
# Unlinked notes
[index](index)
```

I'm using nvim, and my (relevant) .config/nvim/init.vim is:
```
let g:vimwiki_list = [
    \{'path': '/path/to/wiki/', 'syntax': 'markdown', 'ext': '.wiki'}
  \]

" ## vim-zettel
" Filename format. The filename is created using strftime() function
let g:zettel_format = "%Y%m%d-%H%M"

" command used for VimwikiSearch 
" possible values: "ag", "rg", "grep"
let g:zettel_fzf_command = "ag"
```

**Comment by hackabletype** [comment]
`:VimwikiCheckLinks` generates:

```
zettelkasten-inbox.wiki [+]                                                                           3,0-1          Bot
  1 || /path/to/wiki/20200310-1211.wiki is not reachable from the index file
  2 || /path/to/wiki/20200310-1216.wiki is not reachable from the index file
~
~
~
~
~
~
~
~
[Quickfix List] :setqflist()                                                                         1,1             All
```

**Comment by michal-h21** [comment]
Thanks for the report. I've redone the Inbox function and it should detect all unlinked notes now.

**Comment by hackabletype** [comment]
Thanks for the quick fix!

Interesting note now, and this is likely a vim-wiki issue, so I'll probably go and create an issue over there, but `:VimwikiCheckLinks` fails if I use markdown style links (ie, `[Page](link)`) rather than wiki style links (ie: `[[link|Page]]`). And since your new code looks to use the `:VimwikiCheckLinks` function, it seems to have the same issue.

**Comment by michal-h21** [comment]
Ah, I didn't notice this, as I use primarily the Wiki syntax. I think it is reasonable to fix it upstream, in Vimwiki.

**Comment by hackabletype** [comment]
For completeness, here's a link to the upstream issue:
https://github.com/vimwiki/vimwiki/issues/829
