### ISSUE TITLE
Error expanding template

### ISSUE THREAD

**Issue by abers** [michal-h21/vim-zettel#30]
After updating to the latest version of vim-zettel I am now experiencing an error when creating new zettels. I have not changed my vim config or my template file.

```
Error detected while processing function zettel#vimwiki#zettel_new_selected[8]..zettel#vimwiki#zettel_new[25]..zettel
#vimwiki#expand_template:
line    3:
```

My vimrc has:

```
let g:zettel_options = [
                         \{},
                         \ {"front_matter" : {"tags" : ""}, "template" : "~/Dropbox/notes/zettel/template.tpl"}
```

Please let me know what additional info you need to help identify what is causing the error.

**Comment by michal-h21** [comment]
Does the template file `~/Dropbox/notes/zettel/template.tpl` exist?

**Comment by michal-h21** [comment]
Ah, the path had not been expanded, so the template file couldn't be found. It should be fixed now.

**Comment by abers** [comment]
Perfect that's it working again, thank you.
