### ISSUE TITLE
Open Source License?

### ISSUE THREAD

**Issue by Laptop765** [michal-h21/vim-zettel#31]
Thanks for this plugin, it's been fabulous to use and has really changed how I work.

Do you have any plans to release it under an open source license (in a LICENSE file or README.md) for others to contribute?

**Comment by michal-h21** [comment]
Thanks, you are right. I've added a LICENSE file. This project is now licensed under MIT license.

**Comment by Laptop765** [comment]
Awesome, thanks again for such a great plugin!  I'll be sure to contribute back any features and fixes I come up with =)

**Comment by michal-h21** [comment]
Thanks, any fixes are welcome!
