### ISSUE TITLE
ZettelBackLinks error

### ISSUE THREAD

**Issue by prurph** [michal-h21/vim-zettel#34]
Thanks for this cool plugin! I'm experiencing an issue where `VimwikiBacklinks` correctly shows backlinks, but when I run `ZettelBackLinks` I get:

```
Error detected while processing function zettel#vimwiki#backlinks[14]..<SNR>127_insert_link_array:
line    2:
E119: Not enough arguments for function: vimwiki#base#update_listing_in_buffer
```

Any thoughts? The same thing happens for `ZettelGenerateLinks` (`VimwikiGenerateLinks` works).

**Comment by prurph** [comment]
Okay, figured it out. I'm using a later version of vimwiki where the signature of `update_listing_in_buffer` [has changed](https://github.com/vimwiki/vimwiki/blob/dev/autoload/vimwiki/base.vim#L1159). Now it takes a generator for the first argument, and has an additional create argument.

I've never used vimscript before but I got it mostly working by changing `insert_link_array` like this:

```vim
" insert list of links to the current page
function! s:insert_link_array(title, lines)
  let links_rx = '\m^\s*'.vimwiki#u#escape(vimwiki#lst#default_symbol()).' '
  let s:_lines = a:lines
  let GeneratorLinks = copy(l:)
  function! GeneratorLinks.f() abort
    return s:_lines
  endfunction
  call vimwiki#base#update_listing_in_buffer(GeneratorLinks, a:title, links_rx, line('$')+1, 1, 1)
endfunction
```

Now it appears to work, however when updating it doesn't correctly replace the existing block but rather appends all links to the end. I probably have to play around with the second argument, `content_regex`. If anyone has any advice to improve this, I'm all :ear:. Thanks!

**Comment by tiev** [comment]
Thanks for the patch. I have the same problem. Can you create a PR to dev branch?

**Comment by nathanbraun** [comment]
Having the same issue here.

**Comment by bharrisau** [comment]
Came across this just now too. I closed over the arguments

```
" insert list of links to the current page
function! s:insert_link_array(title, lines)
  let links_rx = '\m^\s*'.vimwiki#u#escape(vimwiki#lst#default_symbol()).' '
  let gen = { 'lines': a:lines }

  function! gen.f() abort
      return self.lines
  endfunction

  call vimwiki#base#update_listing_in_buffer(gen, a:title, links_rx, line('$')+1, 1, 1)
endfunction
```
Should also be applied to `zettel#vimwiki#generate_tags` at the end of the file as that also calls `vimwiki#base#update_listing_in_buffer`. That change would look like this


```
  let links_rx = '\m\%(^\s*$\)\|\%('.vimwiki#vars#get_syntaxlocal('rxH2').'\)\|\%(^\s*'
        \ .vimwiki#u#escape(vimwiki#lst#default_symbol()).' '
        \ .vimwiki#vars#get_syntaxlocal('rxWikiLink').'$\)'
  let gen = { 'lines': lines }

  function! gen.f() abort
      return self.lines
  endfunction

  call vimwiki#base#update_listing_in_buffer(gen, 'Generated Tags', links_rx, line('$')+1, 1, 1)
```

**Comment by michal-h21** [comment]
Hi, sorry for the late reply. The support for the current Vimwiki version should work now.
