### ISSUE TITLE
ZettelBackLinks does not detect links when they contain the file extension

### ISSUE THREAD

**Issue by nayssaj** [michal-h21/vim-zettel#38]
When a link contains a file extension (ex: .md), the ZettelBackLinks call returns "No other file links to this file", although there is Zettel linking to the current one.

When removing the file extension, ZettelBackLinks is able to identify the link and create the appropriate backlink.

**Comment by michal-h21** [comment]
You are right. The extension is not used when you create WIki links using the default way (with the `z` key in the visual mode), so I haven't expected it. Does fa17f989b9b36604ddbd67fe97f7fd5de1ea3484 fix this issue for you? It matches optional `.md` extension in the Markdown mode.

**Comment by nayssaj** [comment]
Yes this issue is fixed for me. Thanks a lot for the quick fix.
