### ISSUE TITLE
Searching for titles

### ISSUE THREAD

**Issue by hundredrab** [michal-h21/vim-zettel#39]
Not sure if this is already implemented, but it'd be nice to search through files (something like Ctrl-P but which also works with titles) like `[[` or `ZettleSearch` does currently, but instead of inserting a link, open it instead.

I can use Ctrl-P if I have `%title` in the filename, but I'd rather not go that way.

(Edit): `:Ag` works as expected if vim is opened from the same dir as the wiki, and not when using the `-c VimwikiIndex` command.

**Comment by michal-h21** [comment]
I've added the `:ZettelOpen` command. It uses the same FZF options as `[[`, but it opens the selected page instead.

**Comment by hundredrab** [comment]
This is great, thanks for the quick fix!
