### ISSUE TITLE
Backlinks bug

### ISSUE THREAD

**Issue by brunopc** [michal-h21/vim-zettel#41]
One problem I have had using this command is the following. If file A points to file B and I run `:ZettelBackLinks` in file B, a link to file A will appear in the end of file B, which is fine. However, if I run `:ZettelBackLinks` in file A, it will also show file B in its backlinks, but it is an artificial backlink.

Worse yet is that, if I remove the link from A to B in the body of the note, the links will remain in the Backlinks section.

Is it possible to modify the command so that it ignores links that appear after the Backlinks section?

_Originally posted by @brunopc in https://github.com/michal-h21/vim-zettel/issues/12#issuecomment-627604962_

**Comment by michal-h21** [comment]
@brunopc that is a good idea, I've just implemented that. I hope that it will be not too 

It is possible to change the back links title, using `g:zettel_backlinks_title` variable:

       let g:zettel_backlinks_title = "Backlinks"

**Comment by brunopc** [comment]
Thanks! This is working great here.
