### ISSUE TITLE
vim-zettel initial setup is broken

### ISSUE THREAD

**Issue by gleb108** [michal-h21/vim-zettel#44]
I tried to setup vim-zettel plugin following the README.md

I've got following plugins installed with Vundle
" My Plugins                                                                   |
Plugin 'VundleVim/Vundle.vim'                                       |~                                                                              
Plugin 'vimwiki/vimwiki'                                                   |~                                                                              
Plugin 'junegunn/fzf'                                                        |~                                                                              
Plugin 'junegunn/fzf.vim'                                                 |~                                                                              
Plugin 'michal-h21/vim-zettel'    

```
$ cat .vimrc | grep -v ^\" | grep -v ^$
set nocompatible              " be iMproved, required
filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'vimwiki/vimwiki'
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
Plugin 'michal-h21/vim-zettel'
call vundle#end()            " required
filetype plugin indent on    " required
let g:vimwiki_list = [{'path':'~/vimwiki/','ext':'.md','syntax':'markdown'}, {"path":"~/scratchbox/vimwiki/wiki/"}]
```

When I trying to type :Zettel<TAB> I can see only ZettelCapture and ZettelInsertNote options.
According the documentation there are should be more available commands
Also typing :ZettelNew returns:
E492: Not an editor command: ZettelNew

I think I missed something during initial setup but I can't see any clues at the README.md

**Comment by michal-h21** [comment]
Do you open your wiki using `vim -c VimwikiIndex` or by directly opening of some file in your wiki? Most commands are available only in the wiki mode.

**Comment by gleb108** [comment]
@michal-h21 you are right. I tried to use other commands in usual vim. In wiki mode they works fine . Thanks a lot
BTW what is the right way to keeping images and linking them into markdown files?

**Comment by michal-h21** [comment]
@gleb108 I think the image support depends on the way you will process your Markdown files. I think you can link to images using `![alt text](path to image)`. I would put them in a subdirectory of the wiki.
