### ISSUE TITLE
No possibility to generate markdown friendly links

### ISSUE THREAD

**Issue by nakedpony** [michal-h21/vim-zettel#50]
I would like my zettel to be available on github. So I have my vimwiki configured with `let g:vimwiki_markdown_link_ext = 1`
and it generates links like the following `[title](link.md)` so I can use these links when commiting raw files on github.
But it seems that there is no way to set it up for vim-zettel. It generates links like that: `[200716-1536](200716-1536)`
@michal-h21 could you please let me know if it's possible to configure. Thanks!

**Comment by michal-h21** [comment]
Good point. It was actually quite easy to implement, you can try it already.

**Comment by nakedpony** [comment]
@michal-h21 thanks a lot! Works perfectly now.
