### ISSUE TITLE
Template not applied when using ZettelNew

### ISSUE THREAD

**Issue by adamjt** [michal-h21/vim-zettel#53]
.vimrc
```
Plug 'vimwiki/vimwiki'
Plug 'michal-h21/vim-zettel'
let g:vimwiki_list = [{'path': '~/SynologyDrive/zettelkasten/', 'ext': '.txt'}]
let g:zettel_options = [{'template' : '/Users/adam/.vim/zettel_templates/default.tpl'}]
let g:zettel_format = "%raw_title"
```

I'm using the .txt extension here so I can easily view the files on my phone using the Synology Drive app. The files themselves are in vimwiki syntax.

default.tpl
```
= %title =

```

When using `:ZettelNew Something` a file named `Something.txt` is created, but the contents are using the default template:

```
%title Something
%date 2020-08-05 18:01


```

**Comment by michal-h21** [comment]
Hi, sorry for the late reply. I think this is the same issue as [this one](https://github.com/michal-h21/vim-zettel/issues/59). It should be fixed now.

**Comment by adamjt** [comment]
Thanks! It works better now, but it's appending my template to the default, rather than replacing. I'm gonna see if I can figure it out later today and try to open a PR. If I can't, I'll follow up here!

**Comment by michal-h21** [comment]
Yes, the default headers are always applied, they are independent on the template. Maybe we can introduce a option to disable the default headers?

**Comment by adamjt** [comment]
Oh, sorry for the confusion! I think that would be neat, I keep the pages pretty simple.

**Comment by michal-h21** [comment]
It is possible to disable front matter now, using `disable_front_matter` option:

     let g:zettel_options = [{"template" :  "~/scratchbox/vimwiki/mdtemplate.tpl", "disable_front_matter": 1}]

**Comment by adamjt** [comment]
Thanks so much! Can confirm it works great.
