### ISSUE TITLE
Support backlinks for another type of anchors

### ISSUE THREAD

**Issue by againxx** [michal-h21/vim-zettel#54]
Thank you for this great work!

According to vimwiki's description of anchors, every header, tag, and bold text can be used as anchors.
The `VimwikiBacklinks` command can list all of these types of anchors. However when using `ZettelBackLinks` , it seems only full links without `#` are recognized and generated below the `Backlinks` section.

Output of `VimwikiBacklinks`
![zettel1](https://user-images.githubusercontent.com/22728604/89701328-568b0900-d968-11ea-99a6-a13d113788aa.png)

And output of `ZettelBackLinks`
![zettel2](https://user-images.githubusercontent.com/22728604/89701331-5d198080-d968-11ea-91e6-51f056484e35.png)

Links of this form `[[title#bold text]]` are ignored. A support of titles and bold texts may allow fine-grained references between notes.

**Comment by michal-h21** [comment]
You are right, the regular expression used for back link detection didn't expect anchors. It should be fixed now.

**Comment by againxx** [comment]
Thank you for your quick reply! After updating to the latest version, I came across a new error when I used `ZettelBackLinks`. I am using `dev` branch of `vimwiki`, so maybe due to the interface inconsistency?

![zettel3](https://user-images.githubusercontent.com/22728604/90635415-c1d3b580-e25b-11ea-8264-c2e5629a01eb.png)

**Comment by michal-h21** [comment]
Ah, it seems they removed the variable we used for decting of the development version of Vimwiki, so the version for older versions of Vimwiki was used. I've removed the deprecated code, so it seems to work with both main and devel versions of Vimwiki now.

**Comment by againxx** [comment]
Thank you so much! It works perfectly now!
