### ISSUE TITLE
Unable to select filenames with colons in ZettelSearch 

### ISSUE THREAD

**Issue by csamu** [michal-h21/vim-zettel#55]
You are unable to select and link to notes with colons (:) in their name. 
Selecting a file with a colon in the Ag list will throw an error.

For example:
![image](https://user-images.githubusercontent.com/1021249/90133440-02649800-dd5f-11ea-9e34-6808be780df1.png)

Its probably because of this line:
https://github.com/michal-h21/vim-zettel/blob/f9000b0d080827b7cc5dd036f6043af87b69b86f/autoload/zettel/fzf.vim#L22

**Comment by michal-h21** [comment]
You are right. I've changed the FZF filename handling, so it should work now.
