### ISSUE TITLE
I'm unable to acces any vimwiki mappings and suspect this is the issue...

### ISSUE THREAD

**Issue by 1xch** [michal-h21/vim-zettel#57]
No mappings for this plugin and the vimwiki plugin are loading for me, although <Plug> functions and otherwise appear to work which makes doing anything a gigantic pain. 

The only clue I have now is this from dein log:
```
Error generating helptags:
Vim(helptags):E154: Duplicate tag "g:vimwiki_markdown_link_ext" in file /~/.cache/dein/.cache/init.vim/.dein/doc/zettel.txt
function dein#util#_check_vimrcs[15]..dein#recache_runtimepath[1]..dein#install#_recache_runtimepath[19]..<SNR>150_helptags, line 12
```
Any suggestions or help?

**Comment by michal-h21** [comment]
I've removed the tag header for the `g:vimwiki_markdown_link_ext` variable from the documentation. Does this fix the issue?

**Comment by 1xch** [comment]
That removes the error message, but it does not fix the issue yet, I do not see either vimwiki or vim-zett in my script list, although I can still slowly and manually access functions (e.g. VimwikiUISelect) but not keymappings (e.g. <leader>ws).
