### ISSUE TITLE
template not applied when filename begins with a letter

### ISSUE THREAD

**Issue by chieffoley** [michal-h21/vim-zettel#59]
I changed the default file name to put the date at the end of the file name.  After that I noticed that the template is not automatically applied when creating a new zettel.  I did some experimenting and found that if I put a number at the beginning of the file name, the template works again.

These zettel names will bring in the template automatically:
```
[[2020-08-26-test-z|test-z]]
[[1test-it-2020-08-26|1test-it]]
```
These don't:
```
[[test-it-2020-08-26|test-it]]
[[-test-it-2020-08-26|-test-it]]
```

I would like to have the words come first in the file name, any ideas on how to get that to work?

**Comment by michal-h21** [comment]
Thanks for the report, I can confirm. It should be fixed by 2f56a2140936719f6f18143c9c6a10964d30e97f.

**Comment by chieffoley** [comment]
That fixed it - thanks so much!

**Comment by michal-h21** [comment]
Great! It was luckily easy to fix.
