### ISSUE TITLE
add folgezettel support

### ISSUE THREAD

**Issue by babygau** [michal-h21/vim-zettel#64]
i'm wondering if the plugin could support _folgezettel links_ which is indicated whith tripple bracket `[[[link]]]]`? 

i also include some reference about this type of link:

- [folgezettel heterarchy](https://neuron.zettel.page/2017401.html)
- [understanding folgezettel](https://zettelkasten.de/posts/understanding-hierarchy-translating-folgezettel/)
- [kinds of ties](https://zettelkasten.de/posts/kinds-of-ties)

**Comment by michal-h21** [comment]
Links are handled by Vimwiki, in Markdown mode it supports `[[link|title]]`, or [title](link), which `vim-zettel` uses by default. It seems that `[[[link]]]` is Neuron's extension to Markdown syntax. I don't really understand a need for special folgezettel syntax, I think normal links are perfectly fine for that.

Note that you can have child notes already, using templates. For example if you have the following template:

    #%title 

    Backlink: %backlink
    ----
    %footer

Then a new note created from the existing note using the `z` key will link to the parent note in `%backlink` and insert some shared information from the footer (everything after `----` divider). You can place things like publication references here, for example.

**Comment by babygau** [comment]
thank you @michal-h21, 
you're right that normal link will work just fine. as i'm following this guide [about zettel](https://article69.art.blog/2019/12/20/how-and-why-to-create-a-zettelkasten-a-guide-in-the-vein-of-niklas-luhman/). i found out later that _folgezettel_ is a great way to "branch off" note sequence as illustrated in the following (look at _1a_, _1b_)
![image](https://user-images.githubusercontent.com/1514823/92297766-e8952a00-ef85-11ea-964a-af005e93d9ac.png)
when it comes to searching, a _folgezettel_ syntax (if supported) will stand out and help us to know better about it's relationship with parent zettel rather than just normal back link (aka note sequence _0 1 2 3 .._). 
i'm aware that this is just _cosmetic_ feature but i hope it will be helpful in the long term.
