### ISSUE TITLE
Disable default header

### ISSUE THREAD

**Issue by victorkristof** [michal-h21/vim-zettel#67]
Hi there,

Thanks for the awesome plugin!
I was wondering whether you could add an option to disable the default header?
I'd like to keep my notes rather simple.

Thank you!

[EDIT]: I found that this has already been mentioned is [this issue](https://github.com/michal-h21/vim-zettel/issues/53)!

**Comment by michal-h21** [comment]
This was on my plan, but never managed to do it. It is now possible to disable front matter using `disable_front_matter` option:

      let g:zettel_options = [{"template" :  "~/scratchbox/vimwiki/mdtemplate.tpl", "disable_front_matter": 1}]

**Comment by victorkristof** [comment]
That's super nice!

One little catch, when disabling the front matter and using a template, the first line of a new note is blank.
The template gets pasted on the second line.

Easy to fix?

**Comment by michal-h21** [comment]
Yes, fortunately.

**Comment by victorkristof** [comment]
Awesome, works perfectly! Thanks!
