### ISSUE TITLE
Add %date to template variables

### ISSUE THREAD

**Issue by victorkristof** [michal-h21/vim-zettel#68]
Hi there,

I was expecting the `%date` variable to be rendered when using it in a template, similarly to how it is rendered in the header. But it's not.

Is it a bug or is it a (missing) feature? :)

Thanks!

**Comment by michal-h21** [comment]
Hi, good idea. It should be available now.

**Comment by victorkristof** [comment]
Thanks! Works like a charm :)

(I you're that fast to implement #67 you'll make my Zettelkasten workflow perfect and become my hero of the month 😄)

**Comment by michal-h21** [comment]
Great! These were relatively easy fixes, so I was able to be fast :)
