### ISSUE TITLE
Unknown function fzf#vim#ag

### ISSUE THREAD

**Issue by zoranzaric** [michal-h21/vim-zettel#7]
I have fzf installed but get the error when trying to do a ZettelSearch.

**Comment by michal-h21** [comment]
Thank you for the report. I think you also need [fzf.vim](https://github.com/junegunn/fzf.vim) and [Silver searcher](https://github.com/ggreer/the_silver_searcher). I've updated the README file to include these dependencies.

**Comment by zoranzaric** [comment]
Thanks a lot!  I was confused, that the fzf function is missing.

Would you consider maintaining support for [ripgrep](https://github.com/BurntSushi/ripgrep) feasable?

**Comment by michal-h21** [comment]
@zoranzaric that's a good idea, the command used for searching is now configurable. Try to add the following line to your `.vimrc`:

    let g:zettel_fzf_command = "rg"

**Comment by zoranzaric** [comment]
thanks a lot!
