### ISSUE TITLE
filenames are not sanitized

### ISSUE THREAD

**Issue by heitorPB** [michal-h21/vim-zettel#94]
When I select a few words and press `z`, it creates a new file with those words in the name, but the filename contains spaces. Is there a way to sanitize this? to turn the spaces into hyphens?

This is the config I am using:
```
let g:zettel_format = "%Y-%m-%d-%title"
```

**Comment by MaralWa** [comment]
Hi heitorPB,

just in case you or someone else needs an answer to your question: Just add 'links_space_char': '-' to the options of your wiki, see section `12.3 Per-Wiki Option` in the vimiwiki documentation, `help vimwiki-option-links_space_char`

Ciao

Maral

**Comment by heitorPB** [comment]
Thanks @MaralWa!
